// STD
#include <type_traits>
#include <functional>
#include <string>
#include <memory>
#include <exception>
#include <utility>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <chrono>
#include <new>
#include <limits>
#include <stdexcept>
// STD CONCURRENCY
#include <thread>
#include <atomic>
#include <mutex>
#include <condition_variable>
// STD C
#include <ctime>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cctype>
#include <cstdarg>
#include <cstring>
#include <cstdio>
#include <cstdlib>
// STD STL
#include <algorithm>
#include <vector>
#include <unordered_map>
// LINUX
#ifdef __linux__
#include <string.h>
#include <sched.h>
#include <pthread.h>
#include <syscall.h>
#include <unistd.h>
#include <signal.h>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <linux/user.h>
#include <malloc.h>
#include <pthread.h>
#include <netinet/in.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <sys/select.h>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <fcntl.h>
#include <errno.h>
#include <execinfo.h>
#endif
// WINDOWS
#ifdef _WIN32
#include <direct.h>
#include <Ws2tcpip.h>
#include <windows.h>
#include <malloc.h>
#include <Dbghelp.h>
#endif